apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo
  labels:
    app: node-todo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-todo
      
  template:
    metadata:
      labels:
        app: node-todo
        tier: node-todo
    spec:
      containers:
        - name: node-todo-app
          image: jorgemore/node-todo-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
            name: node-todo-app


---
apiVersion: v1
kind: Service
metadata:
  name: node-todo
  labels:
    app: node-todo
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: node-todo
    tier: node-todo
  type: LoadBalancer
